Matrix style scenarios

diff --git a/.github/workflows/run-scenarios.yaml b/.github/workflows/run-scenarios.yaml
--- a/.github/workflows/run-scenarios.yaml
+++ b/.github/workflows/run-scenarios.yaml
@@ -4,6 +4,9 @@ on:
   pull_request:
 jobs:
   run-scenarios:
+    strategy:
+      matrix:
+        bases: [ development, mainnet, goerli, kovan, fuji ]
     name: Run scenarios
     env:
       ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
@@ -42,16 +45,16 @@ jobs:
         run: npx hardhat compile
 
       - name: Run scenarios
-        run: yarn scenario
+        run: yarn scenario --bases ${{ matrix.bases }}
 
-      - uses: actions/upload-artifact@v2  # upload scenario results
-        if: success() || failure()        # run this step even if previous step failed
+      - uses: actions/upload-artifact@v2 # upload scenario results
+        if: success() || failure() # run this step even if previous step failed
         with:
           name: scenario-results
           path: scenario-results.json
 
       - uses: dorny/test-reporter@v1
         with:
-          name: Scenario Tests              # Name of the check run which will be created
-          path: 'scenario-results.json'     # Path to test results (inside artifact .zip)
-          reporter: mocha-json              # Format of test results
+          name: Scenario Tests # Name of the check run which will be created
+          path: 'scenario-results.json' # Path to test results (inside artifact .zip)
+          reporter: mocha-json # Format of test results
